name: genshin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.1
  http: ^0.13.3
  provider: ^6.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # Usa la versión más reciente

flutter_icons:
  android: true
  ios: False
  image_path: "assets/icon/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/mapas/
    - assets/icon/icon.jpg
